= User Guide
:toclevels: 5
:toc:
// TODO: Soon to be managed by publish workflow
:lib-version: 1.2.57

== Introduction
`ordered` provides sets and maps that preserve insertion order.

== History
`ordered` was originally created by https://github.com/amalloy[Alan Malloy] and was part of the https://github.com/flatland[flatland] organisation.
In December 2018 it was moved to CLJ Commons for continued maintenance.

It could previously be found at https://github.com/amalloy/ordered[amalloy/ordered] and https://github.com/flatland/ordered[flatland/ordered].
https://github.com/clj-commons/ordered[clj-commons/ordered] is the canonical repository now.

== Project Setup

=== Tools Deps
Include the following dependency in your `deps.edn` file:
//:test-doc-blocks/skip
// NOTE: the version in this snippit is automatically updated by our release workflow
[source,clojure,subs="attributes+"]
----
org.flatland/ordered {:mvn/version "{lib-version}"}
----

=== Leiningen
Include the following dependency in your `project.clj` file:
//:test-doc-blocks/skip
// NOTE: the version in this snippit is automatically update by our release workflow
[source,clojure,subs="attributes+"]
----
[org.flatland/ordered "{lib-version}"]
----

=== Babashka
`ordered` is a babashka built-in library.
There is no project setup.

== Supported Envs

For usage from Clojure on the JVM we support:

* JDK 11+ (Clojure 1.13 requires JDK 17+)
* Clojure v1.10.3 and above

For ClojureScript, we support the current release of ClojureScript.

We test on macOS, Windows, and Linux.

== Sets

[source, clojure]
----
(use 'flatland.ordered.set)

(ordered-set 4 3 1 8 2)
=> #ordered/set (4 3 1 8 2)

(conj (ordered-set 9 10) 1 2 3)
=> #ordered/set (9 10 1 2 3)

(into (ordered-set) [7 6 1 5 6])
=> #ordered/set (7 6 1 5)

(disj (ordered-set 8 1 7 2 6) 7)
=> #ordered/set (8 1 2 6)

;; Adding an element already in an ordered set does not change its
;; position in the order.
(conj (ordered-set 4 3 1 8 2) 8)
=> #ordered/set (4 3 1 8 2)

;; Removing an element, then adding it back in, puts it at the end,
;; just as it would if it were never part of the set.
(-> (ordered-set 4 3 1 8 2) (disj 8) (conj 8))
=> #ordered/set (4 3 1 2 8)
----

== Maps

[source, clojure]
----
(use 'flatland.ordered.map)

(ordered-map :b 2 :a 1 :d 4)
=> #ordered/map ([:b 2] [:a 1] [:d 4])

(assoc (ordered-map :b 2 :a 1 :d 4) :c 3)
=> #ordered/map ([:b 2] [:a 1] [:d 4] [:c 3])

(into (ordered-map) [[:c 3] [:a 1] [:d 4]])
=> #ordered/map ([:c 3] [:a 1] [:d 4])

(dissoc (ordered-map :c 3 :a 1 :d 4) :a)
=> #ordered/map ([:c 3] [:d 4])

;; Adding a key already in an ordered map does not change its position
;; in the order.
(assoc (ordered-map :b 2 :a 1 :d 4) :b 7)
=> #ordered/map ([:b 7] [:a 1] [:d 4])

;; Removing a key, then adding it back in, puts it at the end, just as
;; it would if it were never part of the map.
(-> (ordered-map :b 2 :a 1 :d 4) (dissoc :b) (assoc :b 7))
=> #ordered/map ([:a 1] [:d 4] [:b 7])
----

== ClojureScript

Both `flatland.ordered.map` and `flatland.ordered.set` work in ClojureScript.
`#ordered/map` and `#ordered/set` literals are supported in ClojureScript source.

To read them at runtime, register the tags yourself:

[source, clojure]
----
(require '[cljs.reader :as reader]
         '[flatland.ordered.map :as omap]
         '[flatland.ordered.set :as oset])

(reader/register-tag-parser! 'ordered/map omap/ordered-map)
(reader/register-tag-parser! 'ordered/set oset/into-ordered-set)
----

A few things are JVM-only:

* `transient` support
* `flatland.ordered.common/compact`

On ClojureScript, `disj` on an `ordered-set` is O(n) rather than O(1).
