= Developer Guide
:toclevels: 6
:toc:

== Supported Environments
`ordered` is verified on each push on macOS, Ubuntu and Windows via GitHub Actions.

Scripts run on GitHub Actions automatically discover what versions of Clojure to test via auto-discovery of `:clojure-*` aliases in `deps.edn`.
GitHub Actions tests will cover all versions.

JVM tests cover supported LTS JDKs and the current latest JDK.

== Prerequisites
* Java JDK 11 or above (Clojure 1.13+ required JDK 17+)
* Current Clojure CLI
** Note that `ordered` itself supports Clojure v1.10.3 and above
* Current Babashka

== Babashka Tasks
All scripts are written in Clojure and invoked via https://github.com/borkdude/babashka[babashka] tasks.
This gives us a cross platform scripting language that is familiar, fun and consistent.

To see all available tasks with a short description run:
----
bb tasks
----

To run a task, for example, the `test-clj` task:
----
bb test-clj
----

Usage help for a task is requested via `--help`, for example:
----
bb test-clj --help
----

Tasks are described throughout this document.

=== REPLs

To launch a nREPL server:

----
bb dev-jvm
----

From your IDE, cider connect clj to this REPL server.


For a nREPL server that also includes ClojureScript support:

----
bb dev-cljs
----

From your IDE, cider connect cljs to this REPL server.

=== Clean
Sometimes you want to turf any local build work and caches, you can do so via:

----
bb clean
----

=== Unit tests
Unit tests can be run locally on your dev box.
Some tests require a specific os and jdk, you will see warnings if a test is skipped for your current environment.
----
bb test-clj
bb test-cljs
----

=== Checking for Outdated Dependencies

To see what new dependencies are available, run:
----
bb outdated
----

This task uses  https://github.com/liquidz/antq[antq].

=== Linting
We use https://github.com/borkdude/clj-kondo[clj-kondo] and https://github.com/jonase/eastwood[eastwood] to lint rewrite-clj source code.

We fail the build on any lint violations.
The CI server runs:
----
bb lint-kondo
bb lint-eastwood
----
and you can too. The lint script will build the clj-kondo cache when it is missing or stale.
If you want to force a rebuild of the cache run:
----
bb lint-kondo --rebuild
----
